### ISSUE TITLE
Discussion: should OP_CHECKOUTPUT specify an output index?

### ISSUE THREAD

**Issue by pinheadmz** [handshake-org/hsd#224]
OP_CHECKOUTPUT as it is currently implemented gets three values from the stack:

```
const version = stack.getInt(-3, minimal, 4);
const hash = stack.get(-2);
const num = stack.getNum(-1, minimal, 8);
```

... and then compares these with the output _at the same index as the input in which the opcode is executed_:

```
function checkOutput(tx, index, value, version, hash) {
  if (index >= tx.outputs.length)
    return false;

  const output = tx.outputs[index];

  if (output.value !== value)
    return false;

  if (output.address.version !== version)
    return false;

  if (!output.address.hash.equals(hash))
    return false;

  return true;
}
```

This is a cool scheme for coin-spending "covenants" (in the broader meaning of the term) but it is limited by the corresponding-index requirement. Since Handshake `covenants` all very specifically require inputs and outputs to be linked, it prevents them from being combined with OP_CHECKOUTPUT.

### Proposal

OP_CHECKOUTPUT takes one additional parameter off the stack, which specifies an output to introspect and check the other three values.

If that output does not exist, the script fails.

Some of this basic logic already exists. The code could be updated with the minimal diff below. Note that `index` is already declared in the `execute()` function as the index of the input being verified, so during the execution of OP_CHECKOUTPUT we'll need to declare `outputIndex` separately.

```diff
diff --git a/lib/script/script.js b/lib/script/script.js
index 45d6e2f2..d25a01e1 100644
--- a/lib/script/script.js
+++ b/lib/script/script.js
@@ -586,6 +586,7 @@ class Script extends bio.Struct {
           if (stack.length < 3)
             throw new ScriptError('INVALID_STACK_OPERATION', op, ip);

+          const outputIndex = stack.getInt(-4, minimal, 4);
           const version = stack.getInt(-3, minimal, 4);
           const hash = stack.get(-2);
           const num = stack.getNum(-1, minimal, 8);
@@ -600,11 +601,12 @@ class Script extends bio.Struct {
             throw new ScriptError('INVALID_VALUE', op, ip);

           const val = num.isZero() ? value : num.toDouble();
-          const res = checkOutput(tx, index, val, version, hash);
+          const res = checkOutput(tx, outputIndex, val, version, hash);

           stack.pop();
           stack.pop();
           stack.pop();
+          stack.pop();

           stack.pushBool(res);
```

### Use case

This proposal would make on-chain name-for-money atomic swaps simple and flexible.

The name owner just transfers (and finalizes) name ownership to the following script:

```
<OP_TYPE>
<TRANSFER>
<OP_EQUAL>
<OP_IF>
  <1>
  <0>
  <name owner's address hash>
  <price for name in dollarydoos>
  <OP_CHECKOUTPUT>
<OP_ELSE>
  <OP_TYPE>
  <FINALIZE>
  <OP_EQUAL>
<OP_ENDIF>
```

The buyer sends a transaction like so (buyer's money-in and change-out hidden):
```
inputs:
  0:
    prevout: <name owner UTXO>
    script: <empty>
outputs:
  0:
    address: <same script as above, required by covenant rules>
    covenant: <TRANSFER, items: [buyer's address]>
  1:
    address: <version 0> <owner's address hash>
    value: <owner's asking price>
```

Once the `TRANSFER` is confirmed, the buyer finalizes with this transaction:
```
inputs:
  0:
    prevout: <TRASNFER UTXO>
    script: <empty>
outputs:
 0:
    address: <buyer's address>
    covenant: <FINALIZE>
```
